{{- if and .Values.aksConnector.enabled .Values.aksConnector.acdIdentifier }}
{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ required "namespace is missing" .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "4"
    helm.sh/hook-delete-policy: hook-succeeded
type: Opaque
data:
  token: {{ required "spotinst.token is missing" .Values.spotinst.token | b64enc }}
  account: {{ required "spotinst.account is missing" .Values.spotinst.account | b64enc }}
{{- end -}}
{{- end }}
